# Generated by Django 3.2 on 2022-03-04 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('thumbnail', models.ImageField(upload_to='')),
                ('price', models.IntegerField()),
                ('offer_price', models.IntegerField()),
                ('slug', models.SlugField()),
                ('tags', models.TextField()),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('ordered_at', models.CharField(max_length=30)),
                ('is_completed', models.BooleanField()),
                ('productss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product', to='shop.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('categorys', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Category', to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('is_checked', models.BooleanField()),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Products', to='shop.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userss', to='shop.product')),
            ],
        ),
    ]
